spring.application.name=jobhunter

#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3309/job
spring.datasource.username=root
spring.datasource.password=112002
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
###

#config upload file
###
# #default = 1MB
# spring.servlet.multipart.max-file-size=50MB  
# config jwt
###
duy.jwt.base64_secret=hz6xDO2DZ94VEtybyQZDGbLrbyXBppkDudLkG1Dm1/bKTcOIo/mRLQcZGd4abwCBKX1MRH7L19p3VqQFdJsRgA==
# expriration time
duy.jwt.expire_length_second = 360000000
# #default = 10 MB (form data)
# spring.servlet.multipart.max-request-size=50MB
###

